main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('planes/', views.planes_index, name='index'),
    path('planes/<int:plane_id>/', views.plane_detail, name='detail'),
    path('planes/create/', views.PlaneCreate.as_view(), name='planes_create'),
    path('planes/<int:pk>/update/', views.PlaneUpdate.as_view(), name='plane_update'),
    path('planes/<int:pk>/delete/', views.PlaneDelete.as_view(), name='plane_delete'),
    path('planes/<int:plane_id>/add_maintenance/', views.add_maintenance, name='add_maintenance'),
    path('planes/<int:plane_id>/assoc_pilot/<int:pilot_id>/', views.assoc_pilot, name='assoc_pilot'),
    path('planes/<int:plane_id>/unassoc_pilot/<int:pilot_id>/', views.unassoc_pilot, name='unassoc_pilot'),
    path('pilots/', views.PilotList.as_view(), name='pilots_index'),
    path('pilots/<int:pk>/', views.PilotDetail.as_view(), name='pilots_detail'),
    path('pilots/create/', views.PilotCreate.as_view(), name='pilots_create'),
    path('pilots/<int:pk>/update/', views.PilotUpdate.as_view(), name='pilots_update'),
    path('pilots/<int:pk>/delete/', views.PilotDelete.as_view(), name='pilots_delete'),
]

planecollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date

# Create your models here.
class Pilot(models.Model):
    name: models.CharField(max_length=100)
    rating: models.CharField(max_length=10)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('pilots_detail', kwargs={'pk': self.id})

class Plane(models.Model):
    name = models.CharField(max_length=100)
    manufacturer = models.CharField(max_length=100)
    model = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    year = models.IntegerField()
    pilots = models.ManyToManyField(Pilot)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("detail", kwargs={"plane_id": self.id})

class Maintenance(models.Model):
    date = models.DateField('Appointment Date')
    description = models.TextField(max_length=250)
    faarequired = models.BooleanField(
        default=False,
    )

    plane = models.ForeignKey(Plane, on_delete=models.CASCADE)

    class Meta: 
        ordering = ['-date']

main_app/forms.py
from django.forms import ModelForm
from .models import Maintenance

class MaintenanceForm(ModelForm):
    class Meta:
        model = Maintenance
        fields = ['date', 'description', 'faarequired']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from .models import Plane, Pilot
from .forms import MaintenanceForm

# Create your views here.
def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def planes_index(request):
    planes = Plane.objects.all()
    return render(request, 'planes/index.html', { 'planes': planes })

def plane_detail(request, plane_id):
    plane = Plane.objects.get(id=plane_id)
    id_list = plane.pilots.all().values_list('id')
    pilots_plane_doesnt_have = Pilot.objects.exclude(id__in=id_list)
    maintenance_form = MaintenanceForm()
    return render(request, 'planes/detail.html', { 'plane': plane, 'maintenance_form': maintenance_form, 'pilots': pilots_plane_doesnt_have })

def add_maintenance(request, plane_id):
    form = MaintenanceForm(request.POST)
    if form.is_valid():
        new_maintenance = form.save(commit=False)
        new_maintenance.plane_id = plane_id
        new_maintenance.save()
    else: 
        print(form.errors.as_data())
        
    return redirect('detail', plane_id=plane_id)


class PlaneCreate(CreateView):
    model = Plane
    fields = '__all__'
    success_url = '/planes'

class PlaneUpdate(UpdateView):
    model = Plane
    fields = ['name', 'description']

class PlaneDelete(DeleteView):
    model = Plane
    success_url = '/planes'

class PilotList(ListView):
  model = Pilot

class PilotDetail(DetailView):
    model = Pilot

class PilotCreate(CreateView):
  model = Pilot
  fields = '__all__'

class PilotUpdate(UpdateView):
  model = Pilot
  fields = ['name', 'rating']

class PilotDelete(DeleteView):
  model = Pilot
  success_url = '/pilots'

def assoc_pilot(request, plane_id, pilot_id):
  Plane.objects.get(id=plane_id).pilots.add(pilot_id)
  return redirect('detail', plane_id=plane_id)

def unassoc_pilot(request, plane_id, pilot_id):
  Plane.objects.get(id=plane_id).pilots.remove(pilot_id)
  return redirect('detail', plane_id=plane_id)

main_app/templates/about.html
{% extends 'base.html' %} {% block content %}

<h1>About the Plane Collector</h1>
<hr />
<p>Hire the Plane Collector!</p>
<footer>All Rights Reserved, &copy; 2023 Plane Collector</footer>

{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Plane Collector</title>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/style.css' %}"
    />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  </head>
  <body>
    <header class="navbar-fixed">
      <nav>
        <div class="nav-wrapper">
          <ul>
            <li>
              <a href="/" class="left brand-logo"
                >&nbsp;&nbsp;Plane Collector</a
              >
            </li>
          </ul>
          <ul class="right">
            <li><a href="{% url 'about' %}">About</a></li>
            <li><a href="{% url 'planes_create' %}">Add a Plane</a></li>
            <li><a href="{% url 'index' %}">View All My Planes</a></li>
          </ul>
        </div>
      </nav>
    </header>
    <main class="container">{% block content %} {% endblock %}</main>
    <footer class="page-footer">
      <div class="right">
        All Rights Reserved, &copy; 2023 Plane Collector &nbsp;
      </div>
    </footer>
  </body>
</html>

main_app/templates/home.html
{% extends 'base.html' %} {% block content %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <h1>Home</h1>
  </body>
</html>
{% endblock %}

main_app/templates/main_app/plane_confirm_delete.html
{% extends 'base.html' %} {% block content %}
<h1>Delete Plane</h1>

<h4>
  Are you sure you want to delete
  <span class="teal-text">{{ object.name }}</span>?
</h4>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes - Delete!" class="btn" />
  <a href="{% url 'detail' plane.id %}">Cancel</a>
</form>
{% endblock %}

main_app/templates/main_app/plane_form.html
{% extends 'base.html' %} {% block content %} {% if object %}
<h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
<h1>Add Plane</h1>
{% endif %}
<!-- Leaving the action empty makes the form post to the same url used to display it -->
<form action="" method="POST">
  <!-- Django requires the following for security purposes -->
  {% csrf_token %}
  <table>
    <!-- Render the inputs inside of <tr>s & <td>s -->
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit!" class="btn" />
</form>
{% endblock %}

main_app/templates/planes/detail.html
{% extends 'base.html' %} {% block content %}

<h1>Plane Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ plane.name }}</span>
        <p>Manufacturer: {{ plane.manufacturer }}</p>
        <p>Model: {{ plane.model }}</p>
        <p>Description: {{ plane.description|linebreaks }}</p>
        {% if plane.year > 0 %}
        <p>Age: {{ plane.year }}</p>
        {% else %}
        <p>Still in Production</p>
        {% endif %}
      </div>
      <div class="card-action">
        <a href="{% url 'plane_update' plane.id %}">Edit</a>
        <a href="{% url 'plane_delete' plane.id %}">Delete</a>
      </div>
    </div>
  </div>
  <!-- New Markup Below -->
  <div class="col s6">
    <form action="{% url 'add_maintenance' plane.id %}" method="POST">
      {% csrf_token %}
      <!-- Render the inputs -->
      {{ maintenance_form.as_p }}
      <input type="submit" class="btn" value="Add Maintenance" />
    </form>
    <table class="striped">
      <thead>
        <tr>
          <th>Date</th>
          <th>Description</th>
          <th>FAA Requirement</th>
        </tr>
      </thead>
      <tbody>
        {% for maintenance in plane.maintenance_set.all %}
        <tr>
          <td>{{maintenance.date}}</td>
          <td>{{maintenance.description}}</td>
          {% if maintenance.faarequried == True %}
          <td>Yes</td>
          {% else %}
          <td>No</td>
          {% endif %}
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

{% comment %} // {% endcomment %}
<!-- This is all new markup to be added just above the <script> tag -->
<hr />
<div class="row">
  <div class="col s6">
    <h3>{{ plane.name }}'s Pilots</h3>
    {% if plane.pilots.count %} {% for toy in plane.pilots.all %}
    <div class="card">
      <div class="card-content">
        <span class="card-title"> {{ pilot.name }} </span>
      </div>
      <div class="card-action">
        <form action="{% url 'unassoc_toy' cat.id toy.id %}" method="DELETE">
          {% csrf_token %}
          <button type="submit" class="btn">Delete</button>
        </form>
      </div>
    </div>
    {% endfor %} {% else %}
    <h5>No Pilots</h5>
    {% endif %}
  </div>
  <!-- Available toys will come after this line -->
  <div class="col s6">
    <h3>Available Pilots</h3>
    {% if pilots.count %} {% for pilot in pilots.all %}
    <div class="card">
      <div class="card-content">
        <span class="card-title"> {{ pilot.name }} </span>
      </div>
      <div class="card-action">
        <form action="{% url 'assoc_toy' cat.id toy.id %}" method="POST">
          {% csrf_token %}
          <button type="submit" class="btn">Add</button>
        </form>
      </div>
    </div>
    {% endfor %} {% else %}
    <h5>{{plane.name}} Already Has All Pilots Available</h5>
    {% endif %}
  </div>

  <script>
    const dateEl = document.getElementById("id_date");
    // M is Materialize's global variable
    M.Datepicker.init(dateEl, {
      format: "yyyy-mm-dd",
      defaultDate: new Date(),
      setDefaultDate: true,
      autoClose: true,
    });
  </script>
  {% endblock %}
</div>

main_app/templates/planes/index.html
{% extends 'base.html' %} {% block content %}

<h1>Plane List</h1>

{% for plane in planes %}
<div class="card">
  <a href="{% url 'detail' plane.id %}">
    <div class="card-content">
      <span class="card-title">{{ plane.tailNumber }}</span>
      <p>{{ plane.year }}</p>
      <p>Manufacturer: {{ plane.manufacturer }}</p>
      <p>Type: {{ plane.model }}</p>
      {% if plane.year > 0 %}
      <p>Year: {{ plane.year }}</p>
      {% else %}
      <p>Pre-Manufactured</p>
      {% endif %}
    </div>
  </a>
</div>
{% endfor %} {% endblock %}